//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        internal static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, show all.
        /// </summary>
        internal static string DELETE_ASK_CARD_NO {
            get {
                return ResourceManager.GetString("DELETE_ASK_CARD_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will permanently delete all of your notes. Are you sure?.
        /// </summary>
        internal static string DELETE_ASK_CARD_TEXT {
            get {
                return ResourceManager.GetString("DELETE_ASK_CARD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all notes?.
        /// </summary>
        internal static string DELETE_ASK_CARD_TITLE {
            get {
                return ResourceManager.GetString("DELETE_ASK_CARD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, delete all.
        /// </summary>
        internal static string DELETE_ASK_CARD_YES {
            get {
                return ResourceManager.GetString("DELETE_ASK_CARD_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete force.
        /// </summary>
        internal static string DELETE_FORCE {
            get {
                return ResourceManager.GetString("DELETE_FORCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the **delete** command to delete all your notes. You will be prompted before final deletion..
        /// </summary>
        internal static string DELETE_HELP_TEXT {
            get {
                return ResourceManager.GetString("DELETE_HELP_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete notes.
        /// </summary>
        internal static string DELETE_NOTES {
            get {
                return ResourceManager.GetString("DELETE_NOTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All of your **{0} notes** have been **permanently deleted**..
        /// </summary>
        internal static string DELETED_ALL_TEXT {
            get {
                return ResourceManager.GetString("DELETED_ALL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        internal static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a command to learn how to use it..
        /// </summary>
        internal static string HELP_CARD_TEXT {
            get {
                return ResourceManager.GetString("HELP_CARD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help delete.
        /// </summary>
        internal static string HELP_DELETE {
            get {
                return ResourceManager.GetString("HELP_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help note.
        /// </summary>
        internal static string HELP_NOTE {
            get {
                return ResourceManager.GetString("HELP_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help show.
        /// </summary>
        internal static string HELP_SHOW {
            get {
                return ResourceManager.GetString("HELP_SHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HELP_TITLE {
            get {
                return ResourceManager.GetString("HELP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelpType.
        /// </summary>
        internal static string HELP_TYPE {
            get {
                return ResourceManager.GetString("HELP_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsGenericHelp.
        /// </summary>
        internal static string IS_GENERIC_HELP {
            get {
                return ResourceManager.GetString("IS_GENERIC_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no notes to delete..
        /// </summary>
        internal static string NO_NOTES_TO_DELETE {
            get {
                return ResourceManager.GetString("NO_NOTES_TO_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I didn’t get that..
        /// </summary>
        internal static string NOT_UNDERSTOOD {
            get {
                return ResourceManager.GetString("NOT_UNDERSTOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to note.
        /// </summary>
        internal static string NOTE {
            get {
                return ResourceManager.GetString("NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note added successfully!.
        /// </summary>
        internal static string NOTE_ADDED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("NOTE_ADDED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the **note** command to capture a simple note. For example...
        ///
        ///*note call mom tomorrow*
        ///
        ///*note send the project proposal*.
        /// </summary>
        internal static string NOTE_HELP_TEXT {
            get {
                return ResourceManager.GetString("NOTE_HELP_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add text to save the note..
        /// </summary>
        internal static string NOTE_NO_CONTENT {
            get {
                return ResourceManager.GetString("NOTE_NO_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have &lt;b&gt;{0} notes&lt;/b&gt;..
        /// </summary>
        internal static string NOTE_TITLE {
            get {
                return ResourceManager.GetString("NOTE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show.
        /// </summary>
        internal static string SHOW {
            get {
                return ResourceManager.GetString("SHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the **show** command to display all of your notes. You can also display only notes that contain specific words. For example...
        ///
        ///*show*
        ///
        ///*show call mom*
        ///
        ///*show project*.
        /// </summary>
        internal static string SHOW_HELP_TEXT {
            get {
                return ResourceManager.GetString("SHOW_HELP_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show notes.
        /// </summary>
        internal static string SHOW_NOTES {
            get {
                return ResourceManager.GetString("SHOW_NOTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        internal static string USER {
            get {
                return ResourceManager.GetString("USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap welcome_card {
            get {
                object obj = ResourceManager.GetObject("welcome_card", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://notesbotapp.azurewebsites.net/Resources/welcome_card.png.
        /// </summary>
        internal static string WELCOME_CARD_LINK {
            get {
                return ResourceManager.GetString("WELCOME_CARD_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am here to be your assistant and take notes for you..
        /// </summary>
        internal static string WELCOME_CARD_TEXT {
            get {
                return ResourceManager.GetString("WELCOME_CARD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}, I am the Notes bot..
        /// </summary>
        internal static string WELCOME_CARD_TITLE {
            get {
                return ResourceManager.GetString("WELCOME_CARD_TITLE", resourceCulture);
            }
        }
    }
}
