//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QnaBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Qna_Bot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with QnA Service endpoint.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask a question and get the answer(s). Please start the question with **{0}** and end the question with a question mark. For example: What is azure?.
        /// </summary>
        internal static string HELP_ASK_QUESTION_RESPONSE {
            get {
                return ResourceManager.GetString("HELP_ASK_QUESTION_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a command to learn how to use it..
        /// </summary>
        internal static string HELP_CARD_SUBTITLE {
            get {
                return ResourceManager.GetString("HELP_CARD_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HELP_TEXT {
            get {
                return ResourceManager.GetString("HELP_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask a question.
        /// </summary>
        internal static string HELP_TEXT_ASK_QUESTION {
            get {
                return ResourceManager.GetString("HELP_TEXT_ASK_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the FAQ website.
        /// </summary>
        internal static string HELP_TEXT_CHECK_FAQ {
            get {
                return ResourceManager.GetString("HELP_TEXT_CHECK_FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QnA maker was not able to find an answer for your question.
        /// </summary>
        internal static string NO_ANSWER_FOUND {
            get {
                return ResourceManager.GetString("NO_ANSWER_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        internal static string Q_DO {
            get {
                return ResourceManager.GetString("Q_DO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does.
        /// </summary>
        internal static string Q_DOES {
            get {
                return ResourceManager.GetString("Q_DOES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How.
        /// </summary>
        internal static string Q_HOW {
            get {
                return ResourceManager.GetString("Q_HOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there.
        /// </summary>
        internal static string Q_IS_THERE {
            get {
                return ResourceManager.GetString("Q_IS_THERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is.
        /// </summary>
        internal static string Q_WHAT_IS {
            get {
                return ResourceManager.GetString("Q_WHAT_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where.
        /// </summary>
        internal static string Q_WHERE {
            get {
                return ResourceManager.GetString("Q_WHERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are these the questions you want to ask?.
        /// </summary>
        internal static string SUGGESTED_ANSWERS_TITLE {
            get {
                return ResourceManager.GetString("SUGGESTED_ANSWERS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The top {0} answers are:.
        /// </summary>
        internal static string TOP_ANSWERS_TITLE {
            get {
                return ResourceManager.GetString("TOP_ANSWERS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am here to help you find answer(s) to your questions. You can also check the FAQ on the Azure website {0}.
        /// </summary>
        internal static string WELCOME_SUBTITLE {
            get {
                return ResourceManager.GetString("WELCOME_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}, I am the QnA bot.
        /// </summary>
        internal static string WELCOME_TITLE {
            get {
                return ResourceManager.GetString("WELCOME_TITLE", resourceCulture);
            }
        }
    }
}
